{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-gradle-plugin-model",
    "version": "1.7.0-RC",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.7.0-RC"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.0-RC.jar",
          "url": "kotlin-gradle-plugin-model-1.7.0-RC.jar",
          "size": 12107,
          "sha512": "da77d2d5bd1c976e718c5a684e699afa85c1d78e454f760dd34b04a762f565ededf186432029a3ec466b20d3ff93aecae1295dfc17d673a48e9b36979de97005",
          "sha256": "8313cf49e85511411d4c657079b3980dd086ac5d9a42a64ffd357f0db38a192d",
          "sha1": "d1433983de1c4258c9a47c58aacab0a6d7ac70ef",
          "md5": "eef2791622a39ac57fe1cb28f4adfea3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.7.0-RC"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.0-RC.jar",
          "url": "kotlin-gradle-plugin-model-1.7.0-RC.jar",
          "size": 12107,
          "sha512": "da77d2d5bd1c976e718c5a684e699afa85c1d78e454f760dd34b04a762f565ededf186432029a3ec466b20d3ff93aecae1295dfc17d673a48e9b36979de97005",
          "sha256": "8313cf49e85511411d4c657079b3980dd086ac5d9a42a64ffd357f0db38a192d",
          "sha1": "d1433983de1c4258c9a47c58aacab0a6d7ac70ef",
          "md5": "eef2791622a39ac57fe1cb28f4adfea3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.0-RC-sources.jar",
          "url": "kotlin-gradle-plugin-model-1.7.0-RC-sources.jar",
          "size": 7329,
          "sha512": "bf4931f33d1a6e109f6942c84e73fffeb90d6355a8260b3201ae40046949c74f1dfd0d37cfa72e96e01916c024f45e536ccd99a60b6b06ecff73fa5487e67bf9",
          "sha256": "47dd7c06f08839879b11cc54f1bb2853a9001bdb40bba4c8cff4b25136c3bf69",
          "sha1": "aeb5ff4377dd0034b5d20098263636ae00a52b4e",
          "md5": "9e325fce327ede5df7e4ce9e4cfdf3ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.0-RC-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-1.7.0-RC-javadoc.jar",
          "size": 316702,
          "sha512": "d9d0e6d3dcc920017f5aa92a7fcc5118c6fcddb62709cdbb0b7bae11006678dc601e14ada63cdf99f63f1d9b29b2075b82fa4f676b8b0e3ab29bb34385c795cc",
          "sha256": "d9125cca632f4b325891b8bacc8c86c8e5e381459cb27478ace43c1c6f79e5f4",
          "sha1": "632dc292c150c1701e804e9358c19e5e6350c1fa",
          "md5": "824c281c505d17fbde4864f387d3dea0"
        }
      ]
    },
    {
      "name": "gradle70JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.0-RC-gradle70-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-1.7.0-RC-gradle70-javadoc.jar",
          "size": 316702,
          "sha512": "d9d0e6d3dcc920017f5aa92a7fcc5118c6fcddb62709cdbb0b7bae11006678dc601e14ada63cdf99f63f1d9b29b2075b82fa4f676b8b0e3ab29bb34385c795cc",
          "sha256": "d9125cca632f4b325891b8bacc8c86c8e5e381459cb27478ace43c1c6f79e5f4",
          "sha1": "632dc292c150c1701e804e9358c19e5e6350c1fa",
          "md5": "824c281c505d17fbde4864f387d3dea0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "1.7.0-RC"
        }
      ]
    },
    {
      "name": "gradle70SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.0-RC-gradle70-sources.jar",
          "url": "kotlin-gradle-plugin-model-1.7.0-RC-gradle70-sources.jar",
          "size": 7329,
          "sha512": "bf4931f33d1a6e109f6942c84e73fffeb90d6355a8260b3201ae40046949c74f1dfd0d37cfa72e96e01916c024f45e536ccd99a60b6b06ecff73fa5487e67bf9",
          "sha256": "47dd7c06f08839879b11cc54f1bb2853a9001bdb40bba4c8cff4b25136c3bf69",
          "sha1": "aeb5ff4377dd0034b5d20098263636ae00a52b4e",
          "md5": "9e325fce327ede5df7e4ce9e4cfdf3ac"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "1.7.0-RC"
        }
      ]
    },
    {
      "name": "gradle70ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.7.0-RC"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle70"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.0-RC-gradle70.jar",
          "url": "kotlin-gradle-plugin-model-1.7.0-RC-gradle70.jar",
          "size": 12107,
          "sha512": "da77d2d5bd1c976e718c5a684e699afa85c1d78e454f760dd34b04a762f565ededf186432029a3ec466b20d3ff93aecae1295dfc17d673a48e9b36979de97005",
          "sha256": "8313cf49e85511411d4c657079b3980dd086ac5d9a42a64ffd357f0db38a192d",
          "sha1": "d1433983de1c4258c9a47c58aacab0a6d7ac70ef",
          "md5": "eef2791622a39ac57fe1cb28f4adfea3"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "1.7.0-RC"
        }
      ]
    },
    {
      "name": "gradle70RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.7.0-RC"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle70"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.0-RC-gradle70.jar",
          "url": "kotlin-gradle-plugin-model-1.7.0-RC-gradle70.jar",
          "size": 12107,
          "sha512": "da77d2d5bd1c976e718c5a684e699afa85c1d78e454f760dd34b04a762f565ededf186432029a3ec466b20d3ff93aecae1295dfc17d673a48e9b36979de97005",
          "sha256": "8313cf49e85511411d4c657079b3980dd086ac5d9a42a64ffd357f0db38a192d",
          "sha1": "d1433983de1c4258c9a47c58aacab0a6d7ac70ef",
          "md5": "eef2791622a39ac57fe1cb28f4adfea3"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "1.7.0-RC"
        }
      ]
    }
  ]
}
