{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-gradle-plugin-api",
    "version": "1.7.0-RC",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-native-utils",
          "version": {
            "requires": "1.7.0-RC"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-project-model",
          "version": {
            "requires": "1.7.0-RC"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-api-1.7.0-RC.jar",
          "url": "kotlin-gradle-plugin-api-1.7.0-RC.jar",
          "size": 172491,
          "sha512": "ba08b6f670388c1083e190a0621e193012ca2ae4c4f786f56cf2c52177af660bdacb88bef744c298ba65a11234d8fc8d125f4ad23a985cb14755846b45090d34",
          "sha256": "12955fcfc9dfca1ed235fca9399a785818acef5f2365c1a1df8c1b006fbe07be",
          "sha1": "ddd3ab2382c3ecefee5cf24a1b02e41babce4ff5",
          "md5": "f745bbdc711e232f50920f7c8f34c40c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-native-utils",
          "version": {
            "requires": "1.7.0-RC"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-project-model",
          "version": {
            "requires": "1.7.0-RC"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-tooling-core",
          "version": {
            "requires": "1.7.0-RC"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-api-1.7.0-RC.jar",
          "url": "kotlin-gradle-plugin-api-1.7.0-RC.jar",
          "size": 172491,
          "sha512": "ba08b6f670388c1083e190a0621e193012ca2ae4c4f786f56cf2c52177af660bdacb88bef744c298ba65a11234d8fc8d125f4ad23a985cb14755846b45090d34",
          "sha256": "12955fcfc9dfca1ed235fca9399a785818acef5f2365c1a1df8c1b006fbe07be",
          "sha1": "ddd3ab2382c3ecefee5cf24a1b02e41babce4ff5",
          "md5": "f745bbdc711e232f50920f7c8f34c40c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-api-1.7.0-RC-sources.jar",
          "url": "kotlin-gradle-plugin-api-1.7.0-RC-sources.jar",
          "size": 34867,
          "sha512": "9be825d6449efe231b6e937210b5d392a846a224b8a0ed0865f6490114e1deedfcb4c3dec77000548c5a9247eec2602a15e39efcb883533ce5b224bb8438752b",
          "sha256": "4de546f84fe0623c22ad7feb7faca98786b66a1c8872c8fb89ec45cd18c94e9a",
          "sha1": "b1d9cfea68491d1e0f521e6789555ed18efd4066",
          "md5": "a381da0caa5253878e42bdbcce4c4655"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-api-1.7.0-RC-javadoc.jar",
          "url": "kotlin-gradle-plugin-api-1.7.0-RC-javadoc.jar",
          "size": 762601,
          "sha512": "cb29589491d2c03d57c37fcf9e36bf04baee6fe46b9bd205019ffd92da250dd11a3628b22cd165e721e17c7fca9cbf6cf14b245dcd85f903e1a5e222a584f184",
          "sha256": "6e93d41fb40ae303d7086b72524904bafa9e6d650f81c5817aa3768ca74762e3",
          "sha1": "034d7086c031817d3875b0306fdbc0aec286e4c0",
          "md5": "db481ebca26cc8226948a1e91e5a43bf"
        }
      ]
    },
    {
      "name": "gradle70JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-api-1.7.0-RC-gradle70-javadoc.jar",
          "url": "kotlin-gradle-plugin-api-1.7.0-RC-gradle70-javadoc.jar",
          "size": 762608,
          "sha512": "8165f5c50c4bbf34949c68e318e21cebac2b16aa689da16043fd65dae37b49e613575e1c017fe5daa71c20ea12218e54d0ddf7fdece7bcf46760142da580551e",
          "sha256": "d821d6534880e480ee606d0cabca6a4939264a10c33357673d52f0470d16e333",
          "sha1": "aae7b9392e12c9fa95400b395a98ec8faa893257",
          "md5": "418f775eee9f6b83b72ee4ed2c99bfb9"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-api-gradle70",
          "version": "1.7.0-RC"
        }
      ]
    },
    {
      "name": "gradle70SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-api-1.7.0-RC-gradle70-sources.jar",
          "url": "kotlin-gradle-plugin-api-1.7.0-RC-gradle70-sources.jar",
          "size": 34867,
          "sha512": "9be825d6449efe231b6e937210b5d392a846a224b8a0ed0865f6490114e1deedfcb4c3dec77000548c5a9247eec2602a15e39efcb883533ce5b224bb8438752b",
          "sha256": "4de546f84fe0623c22ad7feb7faca98786b66a1c8872c8fb89ec45cd18c94e9a",
          "sha1": "b1d9cfea68491d1e0f521e6789555ed18efd4066",
          "md5": "a381da0caa5253878e42bdbcce4c4655"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-api-gradle70",
          "version": "1.7.0-RC"
        }
      ]
    },
    {
      "name": "gradle70ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-native-utils",
          "version": {
            "requires": "1.7.0-RC"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-project-model",
          "version": {
            "requires": "1.7.0-RC"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-api-1.7.0-RC-gradle70.jar",
          "url": "kotlin-gradle-plugin-api-1.7.0-RC-gradle70.jar",
          "size": 172491,
          "sha512": "ba08b6f670388c1083e190a0621e193012ca2ae4c4f786f56cf2c52177af660bdacb88bef744c298ba65a11234d8fc8d125f4ad23a985cb14755846b45090d34",
          "sha256": "12955fcfc9dfca1ed235fca9399a785818acef5f2365c1a1df8c1b006fbe07be",
          "sha1": "ddd3ab2382c3ecefee5cf24a1b02e41babce4ff5",
          "md5": "f745bbdc711e232f50920f7c8f34c40c"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-api-gradle70",
          "version": "1.7.0-RC"
        }
      ]
    },
    {
      "name": "gradle70RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-native-utils",
          "version": {
            "requires": "1.7.0-RC"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-project-model",
          "version": {
            "requires": "1.7.0-RC"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-tooling-core",
          "version": {
            "requires": "1.7.0-RC"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-api-1.7.0-RC-gradle70.jar",
          "url": "kotlin-gradle-plugin-api-1.7.0-RC-gradle70.jar",
          "size": 172491,
          "sha512": "ba08b6f670388c1083e190a0621e193012ca2ae4c4f786f56cf2c52177af660bdacb88bef744c298ba65a11234d8fc8d125f4ad23a985cb14755846b45090d34",
          "sha256": "12955fcfc9dfca1ed235fca9399a785818acef5f2365c1a1df8c1b006fbe07be",
          "sha1": "ddd3ab2382c3ecefee5cf24a1b02e41babce4ff5",
          "md5": "f745bbdc711e232f50920f7c8f34c40c"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-api-gradle70",
          "version": "1.7.0-RC"
        }
      ]
    }
  ]
}
